name: LaTeX to PDF

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build PDF
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - name: Install texlive
        run: sudo apt install texlive-base

      - name: Install texlive-latex-extra
        run: sudo apt-get install texlive-latex-extra

      - name: Build pdf
        run: pdflatex -jobname resume main.tex

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v3
        with:
          name: resume
          path: resume.pdf

  deploy:
    name: Deploy PDF
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download PDF Artifact
        uses: actions/download-artifact@v3
        with:
          name: resume

      - name: Test artifact download
        run: ls -R

      - name: Create or Update GitHub Release
        id: create_or_update_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            resume.pdf
          tag_name: v.new