name: LateX to PDF

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: resume
          path: outdir/resume.pdf
  release_latex:
    runs-on: ubuntu-latest
    needs: build_latex
    steps:
      - name: remove existing file
        run: rm -f outdir/resume.pdf
      - name: Download PDF file
        uses: actions/download-artifact@v3
        with:
          name: resume
          path: outdir/resume.pdf
      - name: Test artifact download
	run: ls -R
